### ISSUE TITLE
docker run producing strange results

### ISSUE THREAD

**Issue by Harm-Olthof** [efrecon/bawt#1]
Helllo,
Thank you for this Docker image. 
I encounter a problem when I override the entrypoint by another command e.g:
docker run --entrypoint /bin/sh a43f53802488 /bin/sh -c whoami
or 
docker run a43f53802488 /bin/sh -c whoami
gives:
/bin/sh: line 1: can't create ��@а@8: Permission denied
/bin/sh: line 1: ELF: not found
/bin/sh: line 2: p: not found
/bin/sh: line 3: p: not found
/bin/sh: line 1: t: not found
/bin/sh: line 1: ��: not found
/bin/sh: line 1: D��������Q�tdR�td: not found
/bin/sh: line 1: �: not found
/bin/sh: line 4: �����t��: not found
/bin/sh: line 4: �: not found
L�@�DImnstuxyz: not found4.so.1m�!�R
/bin/sh: line 1: �n�镳�: not found
/bin/sh: line 1: M�Z��!9!di9WۓŹ�@9������o�!���7e���ݣk��: not found
/bin/sh: line 1: ���: not found
/bin/sh: line 1: �e�mgUa: not found
/bin/sh: line 6: ~��������2���: not found
/bin/sh: line 7: ����: not found
/bin/sh: line 8: ��: not found
/bin/sh: line 46: syntax error: unexpected ")"

I am on Docker for Desktop 2.2.0.4 on Win10.
(I translated it to the docker cli, but I actualy encounted using this image in a multi-stage setup, using this image)
Regards,
Harm Olthof

**Comment by efrecon** [comment]
This is because I think you have misunderstood the interaction between the command and the entrypoint in general and at the Docker CLI. The command is added after the entrypoint when the container is created and the default command for the `bawt` image is the Tcl shell.

# With an entrypoint

In your first command, you tried to replace the regular entrypoint specified within the `Dockerfile` with yours. You replaced it with the regular shell `/bin/sh`. But then, you give again the shell as an argument to the shell from the entrypoint and the entrypoint shell tries to understand the shell, which is a binary, as a script. You should have written the following instead:

```shell
docker run --entrypoint /bin/sh efrecon/bawt -c "whoami"
```

# Without an entrypoint.

In your second command, pretty much the same happens, except that you are giving `/bin/sh` as an argument to the Tcl shell instead. As the Tcl shell cannot execute commands directly from its argument, I cannot really "correct" the command. But writing something like the following would give you a Tcl prompt:

```shell
docker run -it --rm efrecon/bawt
```

At that prompt, you could send the `whoami` command for execution to Tcl using a command like the following:

```tcl
exec whoami
```

I hope this helps, I will close the issue as it is not a problem with the image.

**Comment by Harm-Olthof** [comment]
you are absolutely right and thank you for your explanation. In the mean time I did figure out how to get it working, but I didn't realize that the shell was trying to interpret the shell-binary. It explains all behavior. Thanks for your response.
